### ISSUE TITLE
Howto mimic sync listener initializer args?

### ISSUE THREAD

**Issue by niksfirefly** [krisleech/wisper-activejob#12]
Is there a way/trick to mimic listener initializer sync args when we use async wisper-activejob?
for example

``` ruby
Wisper.subscribe(MyListener.new(context))
```

where we pass context in initalizer

``` ruby
class Mylistener
  attr_accessor :context
  def initialize(context)
    @context = context
  end

  def create(object)
  end
end
```

**Comment by krisleech** [comment]
If I understand the question then I think the answer is no. Jobs are initialised in a separate process so none of the var's which are in scope when you subscribe the listener will exist when the listener is called by the Job Queue (e.g. Sidekiq). What is `context` can you not initialise a new copy in the listener?
