### ISSUE TITLE
How to subscribe events globally ?

### ISSUE THREAD

**Issue by dfang** [krisleech/wisper-activejob#16]
as readme says,

> The listener must be a class (or module), not an object because of ActiveJob can not reconstruct the state of an object. Whereas a class has no state.

how to subscribe events globally in a initializers.

```
Rails.application.config.to_prepare do
  Wisper.clear if Rails.env.development? || Rails.env.test?
  filenames = Dir.entries('app/subscribers/').reject { |f| File.directory? f }.map { |f| f.gsub!('.rb', '') }
  classes = filenames.map { |f| f.classify.constantize }

  classes.each do |subscriber|
    subscriber = subscriber.name.gsub("Subscriber", "").classify.constantize
    Wisper.subscribe(subscriber, async: true)  # can't subscribe model create/update events
  end
end
```

by the way, this syntax made me confused. 

```
publisher.subscribe(MyListener, async: true)
```
from my understanding, listener is  subscriber, and publisher is broadcaster in some way, 

so i think Subscriber.subscribe(Publisher) is more natural,  Publisher publish events, and Subscriber subscribe events.

correct me please.  :( 

thanks !

**Comment by krisleech** [comment]
This might be better as a question on Stackoverflow, tagged with [wisper](https://stackoverflow.com/questions/tagged/wisper).

I'm not quite sure what you are trying to do, your subscribers should already get required by Rails, so no need for `constantize`. Do you get an error, because `Wisper.subscribe(subscriber, async: true)` looks correct. This should globally subscribe `subscriber`, which should be a class, to every event. Maybe try a simpler case first, e.g.

```ruby
# app/listeners/my_subsriber.rb
class MySubscriber
  def self.hello
    puts "it worked"
  end
end

# initalizer
Wisper.subscribe(MySubscriber, async: true)

# app/models/my_publisher.rb
class MyPublisher
  include Wisper::Publisher

  def call
    broadcast(:hello)
  end
end
```

**Comment by krisleech** [comment]
> so i think Subscriber.subscribe(Publisher) is more natural, Publisher publish events, and Subscriber subscribe events.

You could write a new gem to add this behaviour, please add it to the [wisper wiki](https://github.com/krisleech/wisper/wiki) if you do.

**Comment by dfang** [comment]
@krisleech  thanks for responding. actually, i want to subscribe to all listeners once in initializer. and i've figured it out.

in your example, method hello should be class method if with async: true option

thanks !

**Comment by krisleech** [comment]
I've updated the code for the benefit of any future Googler's.
