### ISSUE TITLE
can u update dependency to rails 4.2.0 ?

### ISSUE THREAD

**Issue by kinnrot** [krisleech/wisper-activejob#2]

**Comment by krisleech** [comment]
Done. Can you try the master branch please and let me know if it works. I'll do a release shortly afterwards.

**Comment by kinnrot** [comment]
There seems to be some problem

Cannot load `Rails.application.database_configuration`:
Could not load database configuration. No such file -
["config/database.yml"](RuntimeError)
  /Users/chen/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/railties-4.2.0/lib/rails/application/configuration.rb:110:in
`database_configuration'
  /Users/chen/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/activerecord-4.2.0/lib/active_record/railtie.rb:117:in
`block (2 levels) in class:Railtie'
  /Users/chen/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/activesupport-4.2.0/lib/active_support/lazy_load_hooks.rb:38:in
`instance_eval'
  /Users/chen/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/activesupport-4.2.0/lib/active_support/lazy_load_hooks.rb:38:in
`execute_hook'
  /Users/chen/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/activesupport-4.2.0/lib/active_support/lazy_load_hooks.rb:45:in
`block in run_load_hooks'
  /Users/chen/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/activesupport-4.2.0/lib/active_support/lazy_load_hooks.rb:44:in
`each'
  /Users/chen/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/activesupport-4.2.0/lib/active_support/lazy_load_hooks.rb:44:in
`run_load_hooks'
  /Users/chen/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/activerecord-4.2.0/lib/active_record/base.rb:316:in
`module:ActiveRecord'
  /Users/chen/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/activerecord-4.2.0/lib/active_record/base.rb:26:in
`<top (required)>'
  /Users/chen/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/devise_invitable-1.4.0/lib/devise_invitable/model.rb:37:in
`block in module:Invitable'
  /Users/chen/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/activesupport-4.2.0/lib/active_support/concern.rb:120:in
`class_eval'
  /Users/chen/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/activesupport-4.2.0/lib/active_support/concern.rb:120:in
`append_features'
  /Users/chen/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/bundler/gems/devise-1094ba65aac1/lib/devise/models.rb:103:in
`include'
  /Users/chen/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/bundler/gems/devise-1094ba65aac1/lib/devise/models.rb:103:in
`block (2 levels) in devise'
  /Users/chen/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/bundler/gems/devise-1094ba65aac1/lib/devise/models.rb:87:in
`each'
  /Users/chen/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/bundler/gems/devise-1094ba65aac1/lib/devise/models.rb:87:in
`block in devise'
  /Users/chen/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/bundler/gems/devise-1094ba65aac1/lib/devise/models.rb:114:in
`devise_modules_hook!'
  /Users/chen/.rbenv/versions/2.1.5/lib/ruby/ge

Chen Kinnrot
kinnrot@gmail.com

**Comment by krisleech** [comment]
What makes you think Wisper is causing this error?

**Comment by kinnrot** [comment]
​It happens only when gem is installed and is in my gemfile..
​

Chen Kinnrot
kinnrot@gmail.com

**Comment by krisleech** [comment]
Have you confirmed you can process jobs without Wisper?

**Comment by kinnrot** [comment]
I'm working on production with active job backed by delayed job for more
then 2 months..

Chen Kinnrot
kinnrot@gmail.com

**Comment by krisleech** [comment]
Can you provide a repo with example app which reproduces the issue?

**Comment by krisleech** [comment]
Did you have any luck with this?

**Comment by craineum** [comment]
FYI, pointing to master allowed me to install on a 4.2.2 project.  Thanks :)

**Comment by krisleech** [comment]
:+1:
