### ISSUE TITLE
Add Rails 5 to Gemfile

### ISSUE THREAD

**Issue by krisleech** [krisleech/wisper-activejob#4]
Change dependency in gemspec to Rails >= 4.2
Add a Gemfile per Rails version.
Use both Gemfile on CI.

**Comment by krisleech** [comment]
WIP https://github.com/krisleech/wisper-activejob/tree/rails5

**Comment by krisleech** [comment]
[CI fails](https://travis-ci.org/krisleech/wisper-activejob/jobs/79811768) with ``require': cannot load such file -- active_job (LoadError)`. No idea why, cannot reproduce locally.

**Comment by dikond** [comment]
Any updates on this? Currently, I have to specify the `gtihub` and `branch` options in `Gemfile`, like so:

`gem 'wisper-activejob', github: 'krisleech/wisper-activejob', branch: 'rails5'`

Would be handy to use just `gem 'wisper-activejob'` : )

**Comment by zillou** [comment]
I've fixed the CI in #13 by updating bundler `before install`.
