### ISSUE TITLE
Add a priority option?

### ISSUE THREAD

**Issue by srpouyet** [krisleech/wisper-activejob#7]
`Wisper:: ActiveJobBroadcaster::Wrapper` has the priority hardcoded to :default. Would it be possible to add an option to set the priority during runtime? Something like: `publisher.subscribe(MyListener, async: true, priority: :low)`

Cheers!

**Comment by krisleech** [comment]
Currently there is no support in Wisper itself to pass arguments to the broadcaster from the subscriber, i.e. `priority: :low`. But this could potentially be a feature for Wisper 2.0, I will look in to the possibility.

If you want to set the same priority for all events broadcast to ActiveJob you could look at passing an argument to the initializer of the [ActiveJob broadcaster](https://github.com/krisleech/wisper-activejob/blob/master/lib/wisper/active_job_broadcaster.rb#L7), and/or providing a setter for priority.

**Comment by krisleech** [comment]
If/when https://github.com/krisleech/wisper-activejob/pull/15 gets merged this will do as you wish. Subscribe to that PR to get updates.
