### ISSUE TITLE
Problem with automatic global id expansion

### ISSUE THREAD

**Issue by antulik** [krisleech/wisper-activejob#8]
we use GlobalId internally to pass object links in events rather than the whole objects. `activejob` gem automatically expands those gid values.

The problem is code which works in sync mode, no longer work in async.

``` ruby
class Listeners::Mailer
  def self.create_comment_successful opts
    comment = GlobalID::Locator.locate opts.fetch(:comment_gid)

    # sync:
    # opts[:comment_gid] === String
    # comment == SomeObject

    # async:
    # opts[:comment_gid] === SomeObject
    # comment == nil 
  end
end
```

This issue makes listeners very easy to break as they will receive different values based on the way the event is passed

**Comment by antulik** [comment]
as a workaround only objects have to be passed and never their gid equivalent

**Comment by krisleech** [comment]
If you broadcast an ActiveRecord object doesn't ActiveJob automatically serialize and deserialize it? So not need for `GlobalID::Locator.locate` inside the listener, it would get the object.

**Comment by antulik** [comment]
yes @krisleech, you are right. We've started with the rule to only serialize primitive types and later added activejob support, which broke our existing implementation. 

I don't think it's a big deal, but was worth it to raise that in case people come across the same issue
